# These values will overwrite the ones in the individual model configuration files.
experiment:
  seed: 28
  num_epochs_ssl: 100
  num_epochs_fine_tuning: 100
  batch_size_fine_tuning: 64

ssl:
  args: []
  kwargs:
    temperature: 0.1
    sample_length: 50
    batch_size: 64
    hidden: [256, 128]
    lr: 0.001
    optimizer_name_ssl: "adam"

    # For CMC-CMKM
    cmkm_config:
      similarity_metric: pretrained_encoder

      intra_modality_negatives_enabled: true
      intra_modality_negatives_weight: 1
      positive_mining_enabled: true
      positive_mining_k: 1

      # Unused in paper.
      positive_mining_symmetric: false
      negative_set_pruning_enabled: false
      negative_set_pruning_threshold: 0.6
      loss_term_weighing_enabled: false
      loss_term_weighing_scale: 0.25

modalities:
  inertial:
    model:
      transformer:
        class_name: SupervisedTransformer
        from_module: inertial
        encoder_class_name: CNNTransformer
        encoder_name: cnn_transformer
        args: []
        kwargs:
          sample_length: 100
          kernel_size: 5
          out_channels: [32, 64, 128]
          num_head: 2
          num_attn_layers: 2
          lr: 0.001
          optimizer_name: "adam"
      ssl:
          args: []
          kwargs:
            lr: 0.001
            sample_length: 100
            hidden: [256, 128]
            temperature: 0.05
            batch_size: 64
            optimizer_name_ssl: "adam"
    transforms:
      - class_name: InertialSampler
        from_module: inertial_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 100
      - class_name: ToTensor
        from_module: general_transforms
        transform_name: to_tensor
        in_test: true
      - class_name: Permute
        from_module: general_transforms
        transform_name: permutation
        in_test: true
        kwargs:
          shape: [1, 0]
      - class_name: ToFloat
        transform_name: to_float
        from_module: general_transforms
        in_test: true

  insole:
    model:
      transformer:
        class_name: SupervisedTransformer
        from_module: insole
        encoder_class_name: CNNTransformer
        encoder_name: cnn_transformer
        args: []
        kwargs:
          sample_length: 100
          kernel_size: 9
          out_channels: [32, 64, 128]
          num_head: 2
          num_attn_layers: 2
          lr: 0.001
          optimizer_name: "adam"
      ssl:
          args: []
          kwargs:
            lr: 0.001
            sample_length: 100
            hidden: [256, 128]
            temperature: 0.05
            batch_size: 64
            optimizer_name_ssl: "adam"
    transforms:
      - class_name: InertialSampler
        from_module: inertial_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 100
      - class_name: ToTensor
        from_module: general_transforms
        transform_name: to_tensor
        in_test: true
      - class_name: Permute
        from_module: general_transforms
        transform_name: permutation
        in_test: true
        kwargs:
          shape: [1, 0]
      - class_name: ToFloat
        transform_name: to_float
        from_module: general_transforms
        in_test: true

